name:                informaticup2022
version:             0.1.0.0
github:              "herrmanno/informaticup2022"
license:             BSD3
author:              "Oliver Herrmann"
maintainer:          "o.herrmann92@gmail.com"
copyright:           "Oliver Herrmann 2021"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/herrmanno/informaticup2022#readme>

dependencies:
- base >= 4.7 && < 5
- containers
- heap
- lens

default-extensions:
- NamedFieldPuns
- FlexibleInstances
- MultiParamTypeClasses
- TypeFamilies
- TemplateHaskell

library:
  source-dirs: src

executables:
  informaticup2022-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - informaticup2022

tests:
  informaticup2022-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - informaticup2022
    - hspec
